name: Feature Request
description: Suggest a new feature or enhancement
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea to improve ScoutAgent? We'd love to hear it!

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is it related to a frustration?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or features you've considered?

  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - Dashboard / UI
        - API Routes
        - Refinery Pipeline
        - Ingest Webhook
        - Authentication
        - Stripe / Billing
        - Alpha Cards
        - New Integration
        - Other
    validations:
      required: true
